<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue"; import { useRoute } from "vue-router"; import { ElMessage } from "element-plus"; import { http } from "../api";
const route=useRoute(), parts=ref<any[]>([]), orders=ref<any[]>([]), partner=ref(""), lines=ref<any[]>([]);
const purchase=computed(()=>route.meta.kind==="purchase"), title=computed(()=>purchase.value?"采购入库":"销售出库");
function add(){lines.value.push({part_id:"",quantity:1,price:0})} function selectPart(line:any){const p=parts.value.find(x=>x.id===line.part_id);line.price=p?(purchase.value?p.purchase_price:p.sale_price):0}
async function load(){parts.value=await http.get("/parts");orders.value=await http.get(purchase.value?"/orders/purchases":"/orders/sales");lines.value=[];add()}
async function submit(){const items=lines.value.filter(x=>x.part_id).map(x=>({part_id:x.part_id,quantity:x.quantity,[purchase.value?"purchase_price":"sale_price"]:x.price}));await http.post(purchase.value?"/orders/purchases":"/orders/sales",{customer_name:purchase.value?undefined:partner.value,items});ElMessage.success(`${title.value}单已保存`);await load()}
watch(()=>route.meta.kind,load);onMounted(load);
</script>
<template><div class="panel order-form"><div class="page-actions"><h3>新建{{title}}单</h3><el-button type="primary" @click="submit">保存并过账</el-button></div><el-input v-if="!purchase" v-model="partner" placeholder="客户名称（可选）" style="width:280px;margin-bottom:14px"/>
<el-table :data="lines"><el-table-column label="零件" min-width="260"><template #default="{row}"><el-select v-model="row.part_id" filterable style="width:100%" @change="selectPart(row)"><el-option v-for="p in parts" :key="p.id" :label="`${p.part_number} · ${p.name}`" :value="p.id"/></el-select></template></el-table-column><el-table-column label="数量"><template #default="{row}"><el-input-number v-model="row.quantity" :min=".001" :precision="3"/></template></el-table-column><el-table-column :label="purchase?'进价(分)':'售价(分)'"><template #default="{row}"><el-input-number v-model="row.price" :min="0"/></template></el-table-column><el-table-column label="金额"><template #default="{row}">¥ {{(row.quantity*row.price/100).toFixed(2)}}</template></el-table-column><el-table-column width="70"><template #default="scope"><el-button link type="danger" @click="lines.splice(scope.$index,1)">移除</el-button></template></el-table-column></el-table><el-button style="margin-top:12px" @click="add">添加一行</el-button></div>
<div class="panel" style="margin-top:18px"><h3>最近{{title}}单</h3><el-table :data="orders"><el-table-column prop="order_no" label="单号"/><el-table-column prop="order_date" label="日期"/><el-table-column prop="order_type" label="类型"/><el-table-column label="金额"><template #default="{row}">¥ {{(row.total_amount/100).toFixed(2)}}</template></el-table-column></el-table></div></template>
