"""init schema

Revision ID: 64e0e278de2e
Revises: 
Create Date: 2026-07-27 15:46:55.618236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e0e278de2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('brand',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('sort_no', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_seq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_rev', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('part',
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('oe_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('brand_id', sa.String(length=26), nullable=True),
    sa.Column('category_id', sa.String(length=26), nullable=True),
    sa.Column('supplier_id', sa.String(length=26), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('max_stock', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('vehicle_models', sa.String(), nullable=True),
    sa.Column('pinyin', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_index('ix_part_category_brand', 'part', ['category_id', 'brand_id'], unique=False)
    op.create_index('ix_part_name', 'part', ['name'], unique=False)
    op.create_index('ix_part_oe_number', 'part', ['oe_number'], unique=False)
    op.create_index('ix_part_pinyin', 'part', ['pinyin'], unique=False)
    op.create_table('purchase_item',
    sa.Column('order_id', sa.String(length=26), nullable=False),
    sa.Column('part_id', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_item_order', 'purchase_item', ['order_id'], unique=False)
    op.create_index('ix_purchase_item_part_created', 'purchase_item', ['part_id', 'created_at'], unique=False)
    op.create_table('purchase_order',
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(length=26), nullable=True),
    sa.Column('order_date', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('source_order_id', sa.String(length=26), nullable=True),
    sa.Column('reversed_by', sa.String(length=26), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('sales_item',
    sa.Column('order_id', sa.String(length=26), nullable=False),
    sa.Column('part_id', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cost_amount', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_item_order', 'sales_item', ['order_id'], unique=False)
    op.create_index('ix_sales_item_part_created', 'sales_item', ['part_id', 'created_at'], unique=False)
    op.create_table('sales_order',
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(length=26), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('order_date', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('received_amount', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('source_order_id', sa.String(length=26), nullable=True),
    sa.Column('reversed_by', sa.String(length=26), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('stock_ledger',
    sa.Column('part_id', sa.String(length=26), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(length=26), nullable=False),
    sa.Column('occurred_at', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_stock_ledger_source')
    )
    op.create_index('ix_stock_ledger_part_occurred', 'stock_ledger', ['part_id', 'occurred_at'], unique=False)
    op.create_table('stock_snapshot',
    sa.Column('part_id', sa.String(length=26), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('avg_cost', sa.Integer(), nullable=False),
    sa.Column('last_in_at', sa.String(), nullable=True),
    sa.Column('last_out_at', sa.String(), nullable=True),
    sa.Column('calc_rev', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('stock_take',
    sa.Column('take_no', sa.String(), nullable=False),
    sa.Column('scope_type', sa.String(), nullable=False),
    sa.Column('scope_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=False),
    sa.Column('posted_at', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('take_no')
    )
    op.create_table('stock_take_item',
    sa.Column('take_id', sa.String(length=26), nullable=False),
    sa.Column('part_id', sa.String(length=26), nullable=False),
    sa.Column('book_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('book_rev', sa.Integer(), nullable=False),
    sa.Column('actual_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('diff_quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('diff_amount', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_take_item_take', 'stock_take_item', ['take_id'], unique=False)
    op.create_table('supplier',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier')
    op.drop_index('ix_stock_take_item_take', table_name='stock_take_item')
    op.drop_table('stock_take_item')
    op.drop_table('stock_take')
    op.drop_table('stock_snapshot')
    op.drop_index('ix_stock_ledger_part_occurred', table_name='stock_ledger')
    op.drop_table('stock_ledger')
    op.drop_table('sales_order')
    op.drop_index('ix_sales_item_part_created', table_name='sales_item')
    op.drop_index('ix_sales_item_order', table_name='sales_item')
    op.drop_table('sales_item')
    op.drop_table('purchase_order')
    op.drop_index('ix_purchase_item_part_created', table_name='purchase_item')
    op.drop_index('ix_purchase_item_order', table_name='purchase_item')
    op.drop_table('purchase_item')
    op.drop_index('ix_part_pinyin', table_name='part')
    op.drop_index('ix_part_oe_number', table_name='part')
    op.drop_index('ix_part_name', table_name='part')
    op.drop_index('ix_part_category_brand', table_name='part')
    op.drop_table('part')
    op.drop_table('customer')
    op.drop_table('change_seq')
    op.drop_table('category')
    op.drop_table('brand')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
